/**
 * PrintLayout — wraps any report template with shared header, footer, and print CSS.
 * Usage:
 *   <PrintLayout reportName="Farmer Ledger" filters={["Farmer: Ali", "Period: Jan 2025"]} printedBy="Manager">
 *     ... report content ...
 *   </PrintLayout>
 *
 * Print pagination design:
 *  - Header and footer are `position: fixed` so the browser repeats them on every printed page.
 *  - The content wrapper reserves matching top/bottom padding so body content never renders
 *    underneath the fixed header/footer on any page (this was the main cause of "collapsing"
 *    layout — header only showed on page 1, and footer could overlap the last lines of content).
 *  - `.print-section` no longer forces `page-break-inside: avoid` by default, because sections
 *    that wrap a long data table (Expense/Sales/Godown/Parcel reports) are often taller than a
 *    single page — forcing them to avoid breaking causes the browser to cut/overlap content
 *    instead of paginating it. Only short, fixed-height blocks (info grids, summaries) opt into
 *    `.print-section-compact` to avoid breaking mid-block.
 */

interface Props {
  reportName: string;
  filters?: string[];
  printedBy?: string;
  farmName?: string;
  children: React.ReactNode;
}

const HEADER_CLEARANCE = 92; // px reserved at top of every printed page for the fixed header
const FOOTER_CLEARANCE = 46; // px reserved at bottom of every printed page for the fixed footer

export const PRINT_CSS = `
  @media print {
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
    html, body { margin: 0; padding: 0; background: white; }
    .no-print, nav, header, .bottom-nav, #root > div > nav { display: none !important; }
    .print-page { display: block !important; }
    @page { size: A4 portrait; margin: 12mm 14mm; }
  }
  .print-page { display: none; }
`;

function PrintHeader({ reportName, filters, printedBy, farmName }: Omit<Props, "children">) {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });

  return (
    <div className="print-header" style={{
      borderBottom: "2.5px solid #1B5E20",
      paddingBottom: 8,
      background: "white",
    }}>
      {/* Top row: logo + title block */}
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <img
            src="/logo.png"
            alt="FaslBook"
            style={{ width: 34, height: 34, objectFit: "contain", borderRadius: 6 }}
            onError={(e) => { (e.currentTarget as HTMLImageElement).style.display = "none"; }}
          />
          <div>
            <div style={{ fontSize: 14, fontWeight: 800, color: "#1B5E20", letterSpacing: 0.5 }}>FaslBook</div>
            <div style={{ fontSize: 8, color: "#555", marginTop: 1 }}>Farm Management System{farmName ? ` — ${farmName}` : ""}</div>
          </div>
        </div>
        <div style={{ textAlign: "right", fontSize: 8, color: "#555", lineHeight: 1.5 }}>
          <div><strong>Generated:</strong> {dateStr} {timeStr}</div>
          {printedBy && <div><strong>Printed By:</strong> {printedBy}</div>}
          {filters && filters.length > 0 && filters.map((f, i) => (
            <div key={i}>{f}</div>
          ))}
        </div>
      </div>
      {/* Report name */}
      <div style={{
        marginTop: 5,
        padding: "3px 0 0 0",
        borderTop: "1px solid #ccc",
        fontSize: 11.5,
        fontWeight: 700,
        color: "#111",
        letterSpacing: 0.3,
      }}>
        {reportName}
      </div>
    </div>
  );
}

function PrintFooter() {
  return (
    <div className="print-footer" style={{
      borderTop: "1px solid #ccc",
      padding: "4px 0 0 0",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      fontSize: 7.5,
      color: "#777",
      background: "white",
    }}>
      <span>Generated by FaslBook — Farm Management System</span>
      <span>Signature: _________________________</span>
      <span className="page-number" />
    </div>
  );
}

export default function PrintLayout({ reportName, filters, printedBy, farmName, children }: Props) {
  return (
    <div className="print-page" style={{
      fontFamily: "'Times New Roman', Times, serif",
      fontSize: 11,
      color: "#111",
      background: "white",
    }}>
      <style>{`
        .print-page {
          font-family: 'Times New Roman', Times, serif;
        }
        .print-header, .print-footer {
          position: static;
        }
        .print-body {
          padding: 0;
        }
        .print-table { width: 100%; border-collapse: collapse; font-family: 'Times New Roman', Times, serif; }
        .print-table th {
          background: #1B5E20 !important; color: white !important;
          padding: 5px 7px; text-align: left; font-size: 9.5pt;
          font-weight: 700; border: 1px solid #155016;
        }
        .print-table td {
          padding: 4px 7px; border: 1px solid #ddd;
          font-size: 9.5pt; vertical-align: top;
        }
        .print-table tr:nth-child(even) td { background: #f9f9f9; }
        .print-table tfoot td {
          font-weight: 700; border-top: 2px solid #1B5E20;
          background: #f0f7f0 !important; color: #1B5E20;
        }
        .print-table .num { text-align: right; }
        .print-table .ctr { text-align: center; }
        .section-title {
          font-size: 10.5pt; font-weight: 700; color: #1B5E20;
          border-bottom: 1px solid #ccc; padding-bottom: 3px; margin: 12px 0 6px 0;
        }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 3px 20px; margin-bottom: 10px; font-size: 9.5pt; }
        .info-grid .label { color: #555; }
        .info-grid .value { font-weight: 600; }
        .summary-row { display: flex; justify-content: space-between; padding: 5px 10px; border: 1px solid #ddd; font-size: 10pt; }
        .summary-row:nth-child(even) { background: #f9f9f9; }
        .summary-row.total { font-weight: 700; border-top: 2px solid #1B5E20; background: #f0f7f0; color: #1B5E20; }

        .print-section { margin-bottom: 12pt; }
        .print-section-compact { page-break-inside: avoid; margin-bottom: 12pt; }

        @media print {
          .print-table th { background: #1B5E20 !important; color: white !important; }
          .print-table thead { display: table-header-group; }
          .print-table tfoot { display: table-footer-group; }
          .print-table tr { page-break-inside: avoid; }
          .print-table tfoot td { background: #f0f7f0 !important; }
          .print-table tr:nth-child(even) td { background: #f9f9f9 !important; }
          .summary-row.total { background: #f0f7f0 !important; }
          .page-break { page-break-before: always; }

          .print-page {
            padding-top: ${HEADER_CLEARANCE}px;
            padding-bottom: ${FOOTER_CLEARANCE}px;
          }
          .print-header {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
          }
          .print-footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
          }
        }
      `}</style>

      <PrintHeader reportName={reportName} filters={filters} printedBy={printedBy} farmName={farmName} />
      <div className="print-body">
        {children}
      </div>
      <PrintFooter />
    </div>
  );
}
